alfredodeza/merfi

LICENSE
By including a copy of the exact MIT license text, we make the terms
of the merfi license very clear.
Also, in the specific case of merfi's MIT license, all derivative
copies of merfi are required to contain the disclaimer text within the
MIT license (as described in the sentence "The above copyright notice
and this permission notice shall be included in all copies or
substantial portions of the Software.") So in order to ease
development and distribution of merfi, it makes sense to simply
include this text in the upstream project.
=> add full MIT license text

merfi/backends/rpm_sign.py, merfi/util.py
Pass the necessary commands to util.run.
In the help text, provide users with a command to look up available keys.
=> rpm_sign: implement the necessary commands

merfi/iso.py, merfi/tests/test_iso.py
With this change, `merfi iso` will create both an ISO file and a matching `.SHA256SUM` file with the checksum of the ISO.
=> iso: also write sha256sum file

merfi/backends/rpm_sign.py, merfi/tests/backends/base.py, merfi/tests/backends/test_gpg.py, merfi/tests/backends/test_rpm_sign.py
The first commit in this PR lays the groundwork for being able to extend BaseBackendTest to test the RpmSign class by refactoring the specific assertions out of the parent class.
The second commit tidies up an issue I encountered while testing with some spurious "Release" files in my tree.
The third commit improves the `--key` argument handling for rpm-sign.
The last commit adds tests for RpmSign.
(The `--keyfile` argument is still not yet functional here, but this PR sets us up to fix that.)
=> test RpmSign class and improve --key arg handling

merfi/backends/gpg.py, merfi/tests/backends/test_gpg.py
The first commit in this PR removes the requirement for the "check" flag (similar to the change that was made for the RpmSign backend in
30698ebf23be3421c743e6720b9205060226ae0b
The second commit removes GpgTest's reliance on `BaseBackendTest`, since that was removed in 94ea9c258d254b371b3ad832cd039c1785f6ca65.
=> fix Gpg backend tests

merfi/iso.py, merfi/tests/test_iso.py
The first commit adds an `argv` argument Iso's `parse_args()`, to make it easier to inject fake values during testing.
The second commit changes the ISO backend to use a better default output filename. (https://github.com/alfredodeza/merfi/issues/15)
The third commit renames one of the test functions to "create_fake_iso()" to more clearly communicate what it does.
The fourth commit adds tests for `make_iso()`.
=> Iso: better default --output, and test make_iso()

README.rst, merfi/backends/rpm_sign.py, merfi/tests/backends/test_rpm_sign.py
When running behind a NAT, the `rpm-sign` command requires a `--nat` flag.
Fixes #18
=> RpmSign: add --nat argument

merfi/backends/gpg.py, merfi/backends/rpm_sign.py, merfi/collector.py, merfi/tests/conftest.py, merfi/tests/test_repocollector.py
Makes the `@staticmethod` go away by re-using the paths in the same class, allows to work with nested repos this way, simplifying the recursive behavior.
=> allow nested repos to be crawled

merfi/tests/backends/test_gpg.py, merfi/tests/backends/test_rpm_sign.py, merfi/tests/conftest.py, merfi/tests/test_repocollector.py
... to make room for an eventual rpm repotree fixture
=> tests: rename repotree fixture for debian

merfi/backends/gpg.py
This is not rST so we don't need this double colon.
=> Gpg: drop duplicate colon ":" in help

merfi/tests/backends/test_rpm_sign.py, merfi/tests/conftest.py, merfi/tests/fixtures/debrepos/nested/dists/trusty/Release, merfi/tests/fixtures/debrepos/nested/dists/xenial/Release
It's getting too complicated to dynamically generate all the necessary files in a realistic way, and this allows us to browse the fixture tree (like with `find` or `ls -R`).
=> tests: use basic files in Git for fixtures

merfi/collector.py
Nothing outside of `RepoCollector` uses this method. Make it private so it's clear that we do not expect external callers to use this.
=> collector: make is_debian_repo() private

merfi/tests/fixtures/debrepos/luminous/dists/trusty/Release, merfi/tests/fixtures/debrepos/luminous/dists/xenial/Release, merfi/tests/test_repocollector.py
Improve the nested repo test a bit by adding a second Ceph release (luminous).
=> tests: add second distro example (luminous)

merfi/backends/gpg.py, merfi/backends/rpm_sign.py, merfi/collector.py, merfi/tests/test_repocollector.py
Prior to this change, RepoCollector stored a list of strs (paths).  The `.debian_release_files` property would simply walk the tree looking for "Release" files, and return them all, even if they were irrelevant for GPG signing.
With this change, RepoCollector stores a list of DebRepo objects instead of strs. The `.debian_release_files` property only returns the specific repository Release file(s) that should be GPG-signed for Apt.
Update the help text for the gpg and rpm-sign backends to clarify that we're seeking and signing repos now, not just any Release files.
=> collector: use DebRepo objects

merfi/backends/gpg.py, merfi/backends/rpm_sign.py
Rather than signing all Release files in the main `sign()` method, break out the Release-file-specific bits into a new smaller method, `sign_release()`.
The purpose of this change is to make room to sign other things here besides Release files.
=> backends: refactor to new sign_release() method

merfi/tests/test_repocollector.py
`RepoCollector` now returns a list of `DebRepos`, not `str`s (paths).  Rename the variable to better reflect this.
=> tests: rename RepoCollector return variable

merfi/tests/test_repocollector.py
Verify that `RepoCollector` returns `DebRepo` objects.
=> tests: add test_debian_repo and test_nested_debian_repo

merfi/backends/gpg.py, merfi/backends/rpm_sign.py, merfi/collector.py
It's better to just interrogate the DebRepo objects directly (with `.releases`) when determining the files to sign. This moves closer to the goal of signing some things that are not Debian repos.
=> backends: drop dependency on RepoCollector's .debian_release_files

merfi/collector.py, merfi/tests/test_repocollector.py
The test suite was the only caller.
=> collector: drop .debian_release_files

merfi/tests/backends/test_rpm_sign.py, merfi/tests/conftest.py, merfi/tests/test_repocollector.py
The `deb_repotree` fixture was going to the work of `os.path.join()` to select "jewel" every time, and then we had further code in the nested tests to undo that work (with `os.path.dirname()`).
Simplify this by returning the parent dir directly in the fixture, and picking "jewel" only for the tests that need it.
=> tests: simplify tree fixtures

merfi/backends/gpg.py
Do not log a general message about what we will run. `util.run()` already logs the exact command that we run each time, so that is more accurate.
This will also no longer be accurate once we start signing RPMs and Yum repodata.
=> Gpg: remove "will sign with the following commands" log

merfi/backends/rpm_sign.py
Prior to this change, if `rpm-sign --clearsign` exited with a non-zero exit code, we would not treat this as fatal, nor log anything at all.
Treat `rpm-sign --clearsign` failures as fatal, sanity-checking the exit code and the resulting stdout string.
=> RpmSign: check --clearsign exit code and stdout

merfi/backends/rpm_sign.py
* RpmSign: nicer logging when writing release.asc
With the switch to using the DebRepo class, we were logging the DebRepo repr when we wrote the release.asc file.  
It's not terrible because the repr does show the path anyway, but it's less noise in the logs to just show the repository's filesystem path instead.
* RpmSign: allow relative paths for --keyfile
We call os.chdir() a lot during signing. Prior to this change, we required the user to specify an absolute path to --keyfile.
Do the absolute path translation ourselves to make this a bit more user-friendly.
=> RpmSign: keyfile UX improvements

merfi/tests/test_repocollector.py
Python does not guarantee os.walk returns results in a particular order.  In some cases (discovered on RHEL 6 / py26 in Koji, exact repro steps unknown), test_nested_debian_repo could fail when repocollector is a list ordered in a way we didn't expect.
Compare the sets in the nested_debian_repo repocollector test, just like we do for the other repocollector tests.
=> tests: compare nested repo test results using sets

merfi/backends/rpm_sign.py
When rpm-sign failed and we entered the failure-checking code path, we
hit a TypeError for merfi.logger:
File "merfi/backends/rpm_sign.py", line 85, in sign
self.sign_release(path)
File "merfi/backends/rpm_sign.py", line 115, in sign_release
self.clear_sign(path, clearsign)
File "merfi/backends/rpm_sign.py", line 44, in clear_sign
logger.error('stderr: %s', line)
TypeError: error() takes exactly 1 argument (2 given)
merfi's custom logger class expects a single "message" argument.
Format the error message strings before passing to the logger.
=> RpmSign: format strings for merfi.logger

README.rst
Prior to this change, the GPG example command and output was not preformatted in reStructuredText. Use the double-colon to tell Sphinx to preformat this.
=> README: fix rST preformatting for gpg example

merfi/logger.py
In Python 3, the output from Popen is bytes, not str. This leads to a crash later on in our logger, because rstrip() does not work on bytes.
Transparently handle bytes messages in our logger by decoding them to strings.
=> logger: handle bytes log messages

tox.ini
Python 3.3 is old. Let's go with the latest that Travis CI supports.
=> tox.ini: Python 3.6

tox.ini
`tox` was not executing `pytest` in any environment except `py26`.
=> tox: execute pytest in all environments

merfi/tests/backends/test_gpg.py, tox.ini
`unittest.mock` is in the stdlib on Python 3.
On Python 2, we need `mock` from PyPI.
=> tests: import mock on py2 and py3
